encryptFilename: false      # En/Decrypt filename. (default false)
exclude: ""                 # Specify file(s) to exclude. Example: "text.txt,image.png,*.zip". (default "")
executableDir: false        # Use path the executable is stored in. (default false)
selectedFiles: []           # Specify file(s) to use exclusively. (default [])
followLinks: false          # Follow links. (default false)
force: false                # Dont ask for confirmation. (default false)
includeBackupFiles: false   # Make backup files (*~,*.bak) selectable. (default false)
includeHiddenFiles: false   # Make hidden files (.*) selectable (default false)
keepInputFiles: false       # Keep the input files. (default false)
mode: ""                    # Specify the mode to use. "e" for encrypt and "d" for decrypt. (default "")
noColor: false              # Disable color. (default false)
noFileTree: false           # Display the files under each over instead of a tree view. (default false)
password: ""                # Specify password to use. Not recommended. (default "")
path: ""                    # Specify path to use. (default "")
recursiveDepth: 0           # Specify the depth of recursive traversal. (default 0)
saltFile: ""                # Specify file to generate salt from
shredInputFiles: false      # Shred (overwrite the input files multiple times) before deletion. (default false)
useGzip: false              # (De)Compress input files using gzip. (default false)
verbose: false              # Print more information. (default false)
